// <auto-generated />
using System;
using CatanUtility.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatanUtility.Web.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20210105040723_HexIndex")]
    partial class HexIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CatanUtility.Classes.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("CatanUtility.Classes.BoardHex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Resource")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Robber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Hexes");
                });

            modelBuilder.Entity("CatanUtility.Classes.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("CatanUtility.Classes.Edge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Occupied")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Edges");
                });

            modelBuilder.Entity("CatanUtility.Classes.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("CatanUtility.Classes.Harbor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("PositionId");

                    b.ToTable("Harbors");
                });

            modelBuilder.Entity("CatanUtility.Classes.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("VictoryPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CatanUtility.Classes.Vertex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Occupied")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Vertices");
                });

            modelBuilder.Entity("CatanUtility.Classes.BoardHex", b =>
                {
                    b.HasOne("CatanUtility.Classes.Board", null)
                        .WithMany("Hexes")
                        .HasForeignKey("BoardId");
                });

            modelBuilder.Entity("CatanUtility.Classes.Card", b =>
                {
                    b.HasOne("CatanUtility.Classes.Player", null)
                        .WithMany("Hand")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("CatanUtility.Classes.Edge", b =>
                {
                    b.HasOne("CatanUtility.Classes.Board", null)
                        .WithMany("Edges")
                        .HasForeignKey("BoardId");
                });

            modelBuilder.Entity("CatanUtility.Classes.Game", b =>
                {
                    b.HasOne("CatanUtility.Classes.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("CatanUtility.Classes.Harbor", b =>
                {
                    b.HasOne("CatanUtility.Classes.Board", null)
                        .WithMany("Harbors")
                        .HasForeignKey("BoardId");

                    b.HasOne("CatanUtility.Classes.Edge", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CatanUtility.Classes.Player", b =>
                {
                    b.HasOne("CatanUtility.Classes.Game", null)
                        .WithMany("Players")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("CatanUtility.Classes.Vertex", b =>
                {
                    b.HasOne("CatanUtility.Classes.Board", null)
                        .WithMany("Vertices")
                        .HasForeignKey("BoardId");
                });

            modelBuilder.Entity("CatanUtility.Classes.Board", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Harbors");

                    b.Navigation("Hexes");

                    b.Navigation("Vertices");
                });

            modelBuilder.Entity("CatanUtility.Classes.Game", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("CatanUtility.Classes.Player", b =>
                {
                    b.Navigation("Hand");
                });
#pragma warning restore 612, 618
        }
    }
}
